### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by clovis1122** [lareenmelo/basic-calculator#2]
So I tried multiplying 2x0.3333333333 and got an unexpected result.

![image](https://user-images.githubusercontent.com/22270042/62437620-f983c400-b711-11e9-96a4-5f067ec70d14.png)

Would be nice to support unlimited precision multiplications or clarify what the rounding rules are somewhere.

**Comment by clovis1122** [comment]
@lareenmelo any update on this?

**Comment by lareenmelo** [comment]
Hi there! This issue has been fixed, however you might find inconsistencies when dealing with really big numbers. This is a fix that will be released sometime in 2020. Thank you for your support!
